import { getProvider } from "./index";
import { scrubGrowwToken } from "./sessionFeed";

// ============================ Groww authentication ============================
// The ACCESS TOKEN is the only Groww credential this app holds. There is no API
// key / API secret flow any more: tokens are generated by the admin on Groww
// (Settings -> Trading APIs) and pasted in, so this app never handles the
// key/secret pair that mints them.
//
// A token is only ever considered valid when a real authenticated Groww request
// succeeds and returns usable data - never because the field is non-empty.

export type GrowwFailureCode =
  | "NO_TOKEN"
  | "INVALID_TOKEN"
  | "AUTH_FAILED"
  | "RATE_LIMIT"
  | "API_UNAVAILABLE"
  | "NETWORK_ERROR"
  | "UNEXPECTED_RESPONSE";

// Human-readable, credential-free explanation per failure kind.
const FAILURE_TEXT: Record<GrowwFailureCode, string> = {
  NO_TOKEN: "No access token saved. Paste a Groww access token and save it.",
  INVALID_TOKEN: "Invalid or expired access token. Groww tokens expire daily (~6:00 AM IST) — generate a fresh one on Groww → Settings → Trading APIs and paste it here.",
  AUTH_FAILED: "Authentication failed. The token was rejected — check the Trading API subscription is active and the token was approved for today.",
  RATE_LIMIT: "Groww is rate-limiting requests right now. Wait a minute and test again.",
  API_UNAVAILABLE: "Groww API is unavailable (server error). This is on Groww's side — try again shortly.",
  NETWORK_ERROR: "Network error reaching Groww. Check this machine's internet connection.",
  UNEXPECTED_RESPONSE: "Unexpected response from the Groww API.",
};

/**
 * Map a thrown provider error onto a failure code + safe message.
 * NEVER includes the access token: the text is scrubbed before being returned.
 */
export function classifyGrowwError(e: unknown): { code: GrowwFailureCode; message: string; detail: string } {
  const raw = scrubGrowwToken((e as any)?.message || String(e || "") || "");
  let code: GrowwFailureCode = "UNEXPECTED_RESPONSE";

  if (/\b401\b|unauthor/i.test(raw)) code = "INVALID_TOKEN";
  else if (/\b403\b|forbidden/i.test(raw)) code = "AUTH_FAILED";
  else if (/\b429\b|rate.?limit|too many/i.test(raw)) code = "RATE_LIMIT";
  else if (/\b5\d\d\b|unavailable|bad gateway/i.test(raw)) code = "API_UNAVAILABLE";
  else if (/fetch failed|network|ENOTFOUND|ECONNREFUSED|ECONNRESET|EAI_AGAIN|timeout|timed out|abort/i.test(raw)) code = "NETWORK_ERROR";

  return { code, message: FAILURE_TEXT[code], detail: raw.slice(0, 200) };
}

export interface GrowwValidation {
  ok: boolean;
  code?: GrowwFailureCode;
  /** Safe, user-facing text. Never contains the token. */
  message: string;
  latencyMs: number;
  /** Proof real data came back (a live/last price), not just a 200. */
  price?: number;
}

/**
 * Makes ONE safe, read-only authenticated Groww request (a single quote) to
 * prove the saved token actually authenticates and returns real data.
 * Read-only by construction — it never places or modifies an order.
 */
export async function validateGrowwToken(timeoutMs = 12_000): Promise<GrowwValidation> {
  const t0 = Date.now();
  try {
    const quote = await Promise.race([
      getProvider().getQuote("RELIANCE.NS"),
      new Promise<never>((_, rej) => setTimeout(() => rej(new Error("Groww request timed out")), timeoutMs)),
    ]);
    const latencyMs = Date.now() - t0;
    const price = Number((quote as any)?.price);
    if (!quote || !Number.isFinite(price) || price <= 0) {
      return { ok: false, code: "UNEXPECTED_RESPONSE", message: "Authenticated, but Groww returned no usable price.", latencyMs };
    }
    return { ok: true, message: `Authenticated — live data received (Reliance ₹${price}).`, latencyMs, price };
  } catch (e) {
    const { code, message } = classifyGrowwError(e);
    return { ok: false, code, message, latencyMs: Date.now() - t0 };
  }
}
