import fs from "fs";
import path from "path";
import { RunSummary } from "./scenarioRunner";

// ============================ QA test-run history ============================
// Append-only JSONL of completed runs (same pattern as loginAudit.ts), plus the
// full result of each run kept alongside so a previous run can be reopened.
// Lives under data/ (gitignored) - it is local QA evidence, not source.

const DIR = path.join(process.cwd(), "data", "qa");
const INDEX = path.join(DIR, "test-runs.jsonl");

export interface RunIndexEntry {
  runId: string;
  startedAt: number;
  finishedAt: number;
  strategyVersion: string;
  commit: string | null;
  strategyHash: string;
  total: number;
  passed: number;
  failed: number;
  unexpected: number;
  noEngineRule: number;
  passPct: number | null;
}

function ensureDir() {
  fs.mkdirSync(DIR, { recursive: true });
}

export function saveRun(summary: RunSummary): void {
  try {
    ensureDir();
    const entry: RunIndexEntry = {
      runId: summary.runId, startedAt: summary.startedAt, finishedAt: summary.finishedAt,
      strategyVersion: summary.strategyVersion, commit: summary.commit, strategyHash: summary.strategyHash,
      total: summary.total, passed: summary.passed, failed: summary.failed,
      unexpected: summary.unexpected, noEngineRule: summary.noEngineRule, passPct: summary.passPct,
    };
    fs.appendFileSync(INDEX, JSON.stringify(entry) + "\n", "utf-8");
    fs.writeFileSync(path.join(DIR, `run-${summary.runId}.json`), JSON.stringify(summary, null, 2), "utf-8");
  } catch { /* QA history is best-effort - never fails a test run */ }
}

/** Most recent runs, newest first. */
export function listRuns(limit = 25): RunIndexEntry[] {
  try {
    const lines = fs.readFileSync(INDEX, "utf-8").split("\n").filter(Boolean);
    return lines.slice(-limit).reverse().map((l) => JSON.parse(l));
  } catch {
    return [];
  }
}

export function readRun(runId: string): RunSummary | null {
  // runId is used in a filename, so allow only the charset generated by
  // newRunId() - never a caller-supplied path fragment.
  if (!/^[A-Za-z0-9_-]{1,64}$/.test(runId)) return null;
  try {
    return JSON.parse(fs.readFileSync(path.join(DIR, `run-${runId}.json`), "utf-8")) as RunSummary;
  } catch {
    return null;
  }
}

/** The newest run, or null when tests have never been executed. */
export function latestRun(): RunSummary | null {
  const [newest] = listRuns(1);
  return newest ? readRun(newest.runId) : null;
}

export function newRunId(): string {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`;
}
